spring.application.name=sistema-colas-uni

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (SQL Server)
# ==========================================

# URL de conexión. Reemplaza 'localhost:1433' si tu servidor está en otra dirección o puerto.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sistemascolasuni;encrypt=true;trustServerCertificate=true;

# Credenciales de acceso. Reemplaza con tu usuario y contraseña de SQL Server.
spring.datasource.username=sa
spring.datasource.password=pMjr2H*eD!R4nh!EMTMS

# Controlador JDBC de SQL Server (Driver)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================

# Dialecto específico para SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Estrategia de inicialización de la base de datos (ddl-auto)
# 'update' creará y modificará las tablas automáticamente sin borrar los datos existentes.
spring.jpa.hibernate.ddl-auto=update

# Mostrar y formatear las consultas SQL generadas en la consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN DE JWT
# ==========================================
# Llave secreta en hexadecimal de 256 bits (HMAC-SHA256)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiración del token de acceso: 15 minutos (900000 ms)
application.security.jwt.expiration=900000
# Expiración del refresh token: 7 días (604800000 ms)
application.security.jwt.refresh-expiration=604800000

# ==========================================
# CONFIGURACIÓN DE SWAGGER / OPENAPI
# ==========================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

